### ISSUE TITLE
Section loses OnClickListener when pinned

### ISSUE THREAD

**Issue by dannyroa** [beworker/pinned-section-listview#15]
The Section that I want to pin has an OnClickListener.

When it is not pinned at the top, the listener works. However, when it is pinned, the listener doesn't work and responds to the Listeners of the view behind the Pinned Section instead.

**Comment by bytebeats** [comment]
@beworker It didn't work, `use OnClickListener attached to the pinned view in adapter`.
@geynen What's your alternative solution?
