### ISSUE TITLE
how to use pinned-section-listview  with CursorAdapter

### ISSUE THREAD

**Issue by lonelysheep** [beworker/pinned-section-listview#51]
when I create my adapter extends CursorAdapter,

@Override
public boolean isItemViewTypePinned(int viewType) {
}
if the viewType has value must override the function  
@Override
public int getItemViewType(int pos) {
  }
and i can't get the item by cursor??
Could give a example when use pinned-section-listview  with CursorAdapter??
will helper me a lot

**Comment by younes0** [comment]
@lonelysheep did you suceed ?
