### ISSUE TITLE
Listview when scroll with shadow?

### ISSUE THREAD

**Issue by MIkeeJY** [beworker/pinned-section-listview#74]
Hi everybody,I found a problem that when listview swipe down,there always with shadow,but I have set  listview.setOverScrollview  "never",but it doesn't  work...

**Comment by MIkeeJY** [comment]
android:overScrollMode="never"
     android:cacheColorHint="#00000000"
Still not work..

**Comment by MIkeeJY** [comment]
Finally,I know it    initShadow(false);

**Comment by Zengminjie** [comment]
hello ,dear author !! personally I think this shadow should be close  as initial ... or at least wrote this function in Readme.md , I hard to distinguish whether it's system 's effect or library 's effect ...and thank @MIkeeJY ,you save my day !!!
