### ISSUE TITLE
Getting error while importing the library in android studio

### ISSUE THREAD

**Issue by hasnain-ahmad** [beworker/pinned-section-listview#80]
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@label value=(@string/app_name) from AndroidManifest.xml:8:9-41
	is also present at [com.madgag:android-pinned-header-listviews:0.4] AndroidManifest.xml:26:18-55 value=(Pinned-Header library).
	Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:5:5-18:19 to override.

**Comment by sergejsha** [comment]
You can use maven integration now. This should solve the issue.
